### ISSUE TITLE
Create a log in page

### ISSUE THREAD

**Issue by Millerbots-2549** [Millerbots-2549/scouting#2]
If multiple schools start using the system we will need to have a log in page. Students will have a unique user id assigned to them and a password. Once the student is logged in we will not need to ask the student to pick their name from a list when completing surveys. Also as part of this change add audit fields to the table so that we can track who and when made data changes.

**Comment by Millerbots-2549** [comment]
Not going to add a password. Just a user id will be sufficient. This userId will need to be passed along on every request and response. The service will not maintain a session. Might still have roles associated to people. Basically just need an admin role so that only a few people have the ability to do admin like things. Normal users will have access to scouting and reporting. If a user does not have a userId they are not able to use the system. UserId must be unique.

**Comment by dchollar** [comment]
Used Spring Boot Security and ThymLeaf and was able to add security. database changes were made.
